# Default values for hello-go-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tjololo/hello-go-web
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"

url: dev.418.cloud

linkerd:
  inject: true

keda:
  scale: true
  threshold: 10
  min: 0
  max: 10
  cooldown: 300