apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "hello-go-web.fullname" . }}
  name: {{ include "hello-go-web.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "hello-go-web.fullname" . }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ include "hello-go-web.fullname" . }}
      {{- if .Values.linkerd.inject }}
      annotations:
        linkerd.io/inject: enabled
      {{- end }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: hello-go-web
        env:
        - name: APP_INFO
          value: "Deploy with helm-chart: {{ include "hello-go-web.chart" . }}"
        readinessProbe:
          failureThreshold: 3
          successThreshold: 1
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 5
          httpGet:
            path: /hello
            port: 8080
        livenessProbe:
          failureThreshold: 3
          successThreshold: 1
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 5
          httpGet:
            path: /hello
            port: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
