apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-dotnet.fullname" . }}-http
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: {{ include "hello-dotnet.fullname" . }}
  sessionAffinity: None
  type: ClusterIP
