apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
  name: {{ include "hello-go-web.fullname" . }}
spec:
  rules:
  - host: {{ .Values.url }}
    http:
      paths:
      - backend:
          serviceName: {{ include "hello-go-web.fullname" . }}
          servicePort: 8080
  tls:
  - hosts:
    - {{ .Values.url }}
    secretName: {{ include "hello-go-web.fullname" . }}